[package]
name = "dojo-fetcher"
version = "0.1.0"
edition = "2021"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const-hex = { version = "1.11.3", features = ["serde"] }
node-semver = "2.1.0"
thiserror.workspace = true
tracing.workspace = true
indicatif.workspace = true
tracing-indicatif.workspace = true
reqwest.workspace = true
serde.workspace = true
log-utils.workspace = true
misc-utils.workspace = true

[dev-dependencies]
hex-literal = "0.4.1"
