[package]
name = "dojo-fetcher_bin"
version = "0.1.0"
edition = "2021"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
reqwest.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["time"] }
tracing.workspace = true
log-utils = { workspace = true, features = ["progress"] }
misc-utils.workspace = true
dojo-fetcher = { path = "../fetcher" }
