[package]
name = "dojo-fetcher_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.4.0", features = ["derive"] }
reqwest = { version = "0.12.4", default-features = false, features = [
  "http2",
  "rustls-tls",
] }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["rt", "time"] }
tracing = "0.1.40"
log-utils = { path = "../../../utils/rs/log-utils" }
misc-utils = { path = "../../../utils/rs/misc-utils" }
dojo-fetcher = { path = "../fetcher" }
