[package]
name = "three-js"
version = "0.1.0"
edition = "2021"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
tracing.workspace = true
thiserror.workspace = true
npm-registry.workspace = true
misc-utils.workspace = true
