[package]
name = "three-js_bin"
version = "0.1.0"
edition = "2021"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
reqwest = { workspace = true, features = ["json", "blocking"] }
clap.workspace = true
three-js = { path = "../fetcher" }
npm-registry.workspace = true
log-utils = { workspace = true, default-features = false }
