[package]
name = "three-js_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.116"
anyhow = "1.0.82"
tracing = "0.1.40"
reqwest = { version = "0.12.4", default-features = false, features = [
  "json",
  "blocking",
  "rustls-tls",
] }
clap = { version = "4.4.0", features = ["derive"] }
three-js = { path = "../fetcher" }
npm-registry = { path = "../../../source/npm/registry" }
log-utils = { path = "../../../utils/rs/log-utils", default-features = false }
